# Generated by Django 5.0.3 on 2024-03-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='name',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='category',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('deluxe', 'Deluxe'), ('suite', 'Suite')], max_length=10),
        ),
    ]
