# Generated by Django 5.0.3 on 2024-03-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_roomtype_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='amenities',
            field=models.CharField(blank=True, choices=[('Standard', 'one bed room, fan, attach bathroom'), ('Deluxe', 'one or double bed room, AC room, attach bathroom, dinning room'), ('Suite', 'one or double bed room, Ac room, attach bathroom, dinning romm, guest room, gym')], max_length=100),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='category',
            field=models.CharField(blank=True, choices=[('Standard', 'standard'), ('Deluxe', 'deluxe'), ('Suite', 'suite')], max_length=10),
        ),
    ]
