# Generated by Django 5.0.3 on 2024-03-13 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_remove_room_room_type_room_roomtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='roomtype',
        ),
    ]
