# Generated by Django 5.0.3 on 2024-03-13 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_remove_booking_room_room_roomtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotel.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.roomtype'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='amenities',
            field=models.CharField(choices=[('Standard', 'One bed room, fan, attached bathroom'), ('Deluxe', 'One or double bed room, AC room, attached bathroom, dining room'), ('Suite', 'One or double bed room, AC room, attached bathroom, dining room, guest room, gym')], max_length=100),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='category',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Deluxe', 'Deluxe'), ('Suite', 'Suite')], max_length=10),
        ),
    ]
