# Generated by Django 5.0.3 on 2024-04-02 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='staff',
            field=models.ForeignKey(choices=[('morning_sift', 'Morining_shift'), ('day_shift', 'Day_shift'), ('night_shift', 'Nignt_shift')], on_delete=django.db.models.deletion.CASCADE, to='hotel.staff'),
        ),
    ]
