# Generated by Django 5.0.3 on 2024-04-18 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0027_alter_task_assigned_to_alter_shift_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(blank=True, choices=[('front_desk', 'Front_Desk'), ('management', 'Management'), ('admin', 'Admin')], max_length=15, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='shift',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.staff'),
        ),
    ]
