# Generated by Django 5.0.3 on 2024-04-18 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0029_alter_shift_end_time_alter_shift_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.staff'),
        ),
    ]
